### ISSUE TITLE
How to use CTSpine1K to train Cervical spine segmentation model？

### ISSUE THREAD

**Issue by Truring** [ICT-MIRACLE-lab/CTSpine1K#2]
Thanks for your contributions!
I download your datasets and want to do segmentations for cervical spine segmentation. But it seems that the floder "HNSCC-3DCT-RT_neck" is the only data I can use, giving other floders doesn't contain areas of cervical spine. But "HNSCC-3DCT-RT_neck" only contain 31 cases. How can I do cervical spine segmentation in this condition like your paper shows?
![image](https://user-images.githubusercontent.com/22017747/122536851-8d857d00-d057-11eb-8aa0-0f7d4de09f43.png)
![image](https://user-images.githubusercontent.com/22017747/122536963-adb53c00-d057-11eb-81f5-b65232408075.png)

**Comment by Sungden** [comment]
You can use our pre-trained model for testing on cervical spine images. You can also train the model from the scratch following the guide on [https://github.com/MIC-DKFZ/nnUNet](url)
Thanks

**Comment by Truring** [comment]
> You can use our pre-trained model for testing on cervical spine images. You can also train the model from the scratch following the guide on [https://github.com/MIC-DKFZ/nnUNet](url)
> Thanks

Thanks for your help! I'll have a shot~
