### ISSUE TITLE
How to make the cervical region look more obvious？

### ISSUE THREAD

**Issue by Truring** [ICT-MIRACLE-lab/CTSpine1K#3]
I use the software MRIcron to view nii.gz files in folder "HNSCC-3DCT-RT_neck". And it looks like this.
![image](https://user-images.githubusercontent.com/22017747/123081461-8e9c1d00-d450-11eb-9928-dd4840958988.png)
![image](https://user-images.githubusercontent.com/22017747/123081496-978cee80-d450-11eb-9880-ca72a965f9f9.png)

How to make the cervical region look more obvious？Like the images in your paper, 
![image](https://user-images.githubusercontent.com/22017747/123081670-c99e5080-d450-11eb-9896-803a60ce7125.png)

**Comment by Sungden** [comment]
You can change the window width or use the software ITK-SNAP.

**Comment by Truring** [comment]
> You can change the window width or use the software ITK-SNAP.

Thank you for your quick reply. And it works with ITK-SNAP.
