### ISSUE TITLE
Train/val/test split and provided model weights

### ISSUE THREAD

**Issue by duducheng** [ICT-MIRACLE-lab/CTSpine1K#4]
Hi,

Thank you for providing such an amazing dataset ;)

I would like to know how to compare with the provided nnUNet baseline. What's the exact dataset split? Could u provide the the data split-id correspondence so that we could compare our own method with your baseline model weights?

Cheers,
Jiancheng Yang

**Comment by Sungden** [comment]
Thanks for your interest. You can find the dataset split on our provided google drive storage. 
Best
